### ISSUE TITLE
请问ubuntu14.04环境下该插件安装后乱码是什么原因？

### ISSUE THREAD

**Issue by KingRumn** [1ball/MyWorkEnv#4]
https://github.com/1bool/MyWorkEnv/blob/279a49fcbc561431d09fb33efcf4f63dc59ea6fa/vim/plugrc.vim#L27

**Comment by 1bool** [comment]
我在14.04 32bit环境下用没有乱码啊。你会不会是在终端里用，然后终端字体用的默认的，没有选择powerline字体？终端字体没有自动改，默认字体有些符号可能会乱码。
